# Generated by Django 4.2.6 on 2023-10-22 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribers',
            name='email',
            field=models.EmailField(error_messages={'blank': 'Please enter your email.', 'invalid': 'Please enter a valid email address.', 'null': 'Please enter your email.', 'unique': 'This email has already been registered.'}, max_length=254, unique=True),
        ),
    ]
